apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_HOST: "{{ .Release.Name }}-mysql"
  DB_PORT: "3306"
  DB_DATABASE: "{{ .Values.database.name }}"
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
