{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .port }}
      targetPort: 80
{{- end }}
