apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-notificationservice-config
  namespace: {{ .Values.global.namespace }}
data:
  DB_CONNECTION: "mysql"
  DB_HOST: "{{ .Values.database.host }}"
  DB_PORT: "{{ .Values.database.port }}"
  DB_DATABASE: "{{ .Values.notificationservice.env.DB_DATABASE }}"
  DB_USERNAME: "{{ .Values.notificationservice.env.DB_USERNAME }}"
  DB_PASSWORD: "{{ .Values.notificationservice.env.DB_PASSWORD }}"
