apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-orderservice-config
  namespace: {{ .Values.global.namespace }}
data:
  DB_CONNECTION: "mysql"
  DB_HOST: "{{ .Values.database.host }}"
  DB_PORT: "{{ .Values.database.port }}"
  DB_DATABASE: "{{ .Values.orderservice.env.DB_DATABASE }}"
  DB_USERNAME: "{{ .Values.orderservice.env.DB_USERNAME }}"
  DB_PASSWORD: "{{ .Values.orderservice.env.DB_PASSWORD }}"
  BILLING_SERVICE_URL: "{{ .Values.orderservice.env.BILLING_SERVICE_URL }}"
  NOTIFICATION_SERVICE_URL: "{{ .Values.orderservice.env.NOTIFICATION_SERVICE_URL }}"
