apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-billingservice-config
  namespace: {{ .Values.global.namespace }}
data:
  DB_CONNECTION: "mysql"
  DB_HOST: "{{ .Values.database.host }}"
  DB_PORT: "{{ .Values.database.port }}"
  DB_DATABASE: "{{ .Values.billingservice.env.DB_DATABASE }}"
  DB_USERNAME: "{{ .Values.billingservice.env.DB_USERNAME }}"
  DB_PASSWORD: "{{ .Values.billingservice.env.DB_PASSWORD }}"
