apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-auth
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://authservice.{{ .Values.global.namespace }}.svc.cluster.local:8080/api/auth/validate-token"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-User-Id"
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /api/auth/validate-token
            pathType: Prefix
            backend:
              service:
                name: authservice
                port:
                  number: 8080
          - path: /api/auth/logout
            pathType: Prefix
            backend:
              service:
                name: authservice
                port:
                  number: 8080

          - path: /api/user
            pathType: Prefix
            backend:
              service:
                name: userservice
                port:
                  number: 8081

          - path: /api/orders
            pathType: Prefix
            backend:
              service:
                name: orderservice
                port:
                  number: 8082

          - path: /api/billing
            pathType: Prefix
            backend:
              service:
                name: billingservice
                port:
                  number: 8083

          - path: /api/notifications
            pathType: Prefix
            backend:
              service:
                name: notificationservice
                port:
                  number: 8084
