apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: users-crud
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: users-crud
  template:
    metadata:
      labels:
        app: users-crud
    spec:
      containers:
        - name: users-crud
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-db-secret
