apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.database.user | b64enc }}
  DB_PASSWORD: {{ .Values.database.password | b64enc }}
