{
 "title": "HW5",
 "time": { "from": "2025-03-01T21:28:35.274Z", "to": "2025-03-01T21:34:46.438Z" },
 "panels": [
  {
   "title": "Latency(quantile 0.99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, method, exported_endpoint) (rate(users_crud_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method, exported_endpoint) (\n  rate(users_crud_http_requests_total[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency(quantile 0.95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, method, exported_endpoint) (rate(users_crud_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (method, exported_endpoint)(rate(users_crud_http_errors_total{status=\"500\"}[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency(quantile 0.5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, method, exported_endpoint) (rate(users_crud_http_request_duration_seconds_bucket[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}