apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: ksarien/otus-users-crud:2.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-credentials
          command: ["php", "artisan", "migrate", "--force"]
      restartPolicy: OnFailure
